{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "mern-secret" }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.secret.type | default "Opaque" }}
stringData:
  mongo-uri: {{ .Values.secret.data.mongoUri | quote }}
  jwt-secret: {{ .Values.secret.data.jwtSecret | quote }}
  slack-webhook-url: {{ .Values.secret.data.slackWebhookUrl | quote }}
{{- end }}
